spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/school_db
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: never
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml